### ISSUE TITLE
项目启动后页面没有内容显示

### ISSUE THREAD

**Issue by yyymini** [yoyoyohamapi/self-government-component-with-redux-observable#1]
大佬，我项目启动后，没有显示内容。我系统是win 10,会不会是系统差异。

**Comment by yoyoyohamapi** [comment]
> 大佬，我项目启动后，没有显示内容。我系统是win 10,会不会是系统差异。

没问题啊，启动要些时间

**Comment by yyymini** [comment]
最终定位到了这里 把webpack里 publicPath: path.resolve(__dirname, '/') ，改成publicPath:"/"  ，就可以正常运行了。不是很懂，可能是系统环境差异？

**Comment by yyymini** [comment]
> > 大佬，我项目启动后，没有显示内容。我系统是win 10,会不会是系统差异。
> 
> 没问题啊，启动要些时间

感谢回复，我关掉了哈。
